#mybatis-plus:
#  global-config:
#    db-config:
#      # 逻辑已删除值(默认为 1)
#      logic-delete-value: 1
#      # 逻辑未删除值(默认为 0)
#      logic-not-delete-value: 0
#      # 全局唯一ID，Long类型的主键
#      id-type: id_worker
  # logback打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl